name: UnPack CI

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

env:
  PANVIMDOC_COMMIT_MSG: "docs(panvimdoc): automated doc generation"

jobs:
  style:
    if: github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, 'env.PANVIMDOC_COMMIT_MSG')
    name: Run stylua check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          args: --check .
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

  tests:
    if: github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, 'env.PANVIMDOC_COMMIT_MSG')
    name: Run tests with busted
    needs: style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Neovim
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Install luarocks
        run: sudo apt-get install -y luarocks

      - name: Install busted
        run: luarocks install busted --local

      - name: Run tests
        run: |
          export PATH=$HOME/.luarocks/bin:$PATH
          export LUA_PATH="?.lua;?/init.lua;./lua/?.lua;./lua/?/init.lua;$HOME/.luarocks/share/lua/5.1/?.lua;$HOME/.luarocks/share/lua/5.1/?/init.lua;./lua_modules/?.lua;./lua_modules/?/init.lua;$LUA_PATH"
          nvim --headless -c "!busted --verbose ." -c "qa!"

  docs:
    if: github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, 'env.PANVIMDOC_COMMIT_MSG')
    name: Generate docs with panvimdoc
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}-nvim

      - name: Set up git with PAT
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PANVIMDOC }}@github.com/${{ github.repository }}.git

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          commit_message: ${{ env.PANVIMDOC_COMMIT_MSG }}
